### ISSUE TITLE
This repository is a LIE and should be removed or at least add a working playable game in it!

### ISSUE THREAD

**Issue by PhilHubNew2022** [AwokeinanEnigma/Mother4_MerylEdition#1]
I just tested the thing myself and was asking for help because the one the user sent me had the game but crashed upon starting a new game! Enigma is a idiot. I am surprised why you even bothered trying to revive it when you give us a broken and misleading repository here lmao. No wonder Oddity team take down all of your links on the reddit. I will never trust you again, scumbag. 

Again, the repository is very misleading and there is NO playable build in it, despite Enigma claimed he "put all his efforts into making Mother 4 a playable game" eh I don't know why would this guy say it but I think he is someone from the team only trying to troll us into thinking the real thing was finally here. Winter 2014 will never come lmao. 

I would also like to bring up about what happened last night, I tried to run the game he sent me, which was the one he never provided here on this repo, although it played fine when I was fooling around with the map test mode. However, starting a new game or continue will crash the game! I don't know why this happens and I ask the creator of this repo (Enigma) for help and all he did was banned me from his own discord server! Enigma never helped me at all and he did NOTHING to improve or help make this thing work.  

This repo is a giant lie and should be removed soon. 

Making broken or misleading repos should be against Github policy!

Screw you Enigma!

**Comment by PhilHubNew2022** [comment]
> First of all, you like children. I don't even have to elaborate you're just weird and unpleasant to deal with.

Call me a child if you want but the reality is you don't seem to know how to make a repository or you only making this demo to make a fool out of us? We want a working restored version of this game and not a broken repo that only works with map mode instead of starting a new game. I will report you and your repo if you don't fix this.

**Comment by AwokeinanEnigma** [comment]
Feel free to dude, I literally haven't violated any rules. Besides I also told you how to fix the problem.
